name: Build Lightweight Tunnel

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    # 1. 拉取代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 配置 Go 环境
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    # 3. 编译
    - name: Build Binary
      run: |
        go build -v -o lightweight-tunnel-linux-amd64 ./cmd/lightweight-tunnel

    # 4. 上传打包结果
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lightweight-tunnel-linux-amd64
        path: lightweight-tunnel-linux-amd64

  build-macos-amd64:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        brew install libpcap

    - name: Build Binary
      run: |
        CGO_ENABLED=1 go build -v -o lightweight-tunnel-macos-amd64 ./cmd/lightweight-tunnel

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lightweight-tunnel-macos-amd64
        path: lightweight-tunnel-macos-amd64

  build-macos-arm64:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        brew install libpcap

    - name: Build Binary
      run: |
        CGO_ENABLED=1 GOARCH=arm64 go build -v -o lightweight-tunnel-macos-arm64 ./cmd/lightweight-tunnel

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lightweight-tunnel-macos-arm64
        path: lightweight-tunnel-macos-arm64
